name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: before_script
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose
    - name: script
      run: docker-compose run app sh -c "python manage.py test && flake8"
